In [155]:
import pandas as pd
#df1 is for wheat
df1 = pd.read_excel("/content/Ukraine Russia Food Insights - ukraine-russia-food.xlsx",sheet_name = "wheat")
#df2 is for maize
df2 = pd.read_excel("/content/Ukraine Russia Food Insights - ukraine-russia-food.xlsx",sheet_name = "maize")
#df3 is for barley
df3 = pd.read_excel("/content/Ukraine Russia Food Insights - ukraine-russia-food.xlsx",sheet_name = "barley")
#df4 is for sunflower
df4 = pd.read_excel("/content/Ukraine Russia Food Insights - ukraine-russia-food.xlsx",sheet_name = "sunflower")

In [156]:
#checking for missing values
missing_values = df1.isnull().sum()
print("Missing Values:\n", missing_values)

Missing Values:
 Domestic wheat supply                                 0
Wheat exports                                       613
Wheat imports                                       117
Wheat stocks                                          0
Net wheat imports                                   616
Wheat imports (% domestic supply)                   912
Wheat stocks (% domestic supply)                      0
Wheat exports per capita                            613
Wheat imports per capita                            117
Net wheat imports per capita                        616
Wheat stocks per capita                               0
Domestic wheat per capita                             0
Wheat imports from Ukraine                         1346
Wheat imports from Russia                          1167
Wheat imports from Ukraine + Russia                1441
Wheat imports from Ukraine per capita              1346
Wheat imports from Russia per capita               1167
Wheat imports from Ukraine + Russia per capita     1441
Wheat imports from Ukraine (% imports)             1346
Wheat imports from Russia (% imports)              1167
Wheat imports from Ukraine + Russia (% imports)    1441
Wheat imports from Ukraine (% supply)              1346
Wheat imports from Russia (% supply)               1167
Wheat imports from Ukraine + Russia (% supply)     1441
Entity                                                0
Year                                                  0
dtype: int64

In [157]:
#checking datatype
data_types = df1.dtypes
print("\nData Types:\n", data_types)

Data Types:
 Domestic wheat supply                                int64
Wheat exports                                      float64
Wheat imports                                      float64
Wheat stocks                                         int64
Net wheat imports                                  float64
Wheat imports (% domestic supply)                  float64
Wheat stocks (% domestic supply)                   float64
Wheat exports per capita                           float64
Wheat imports per capita                           float64
Net wheat imports per capita                       float64
Wheat stocks per capita                            float64
Domestic wheat per capita                          float64
Wheat imports from Ukraine                         float64
Wheat imports from Russia                          float64
Wheat imports from Ukraine + Russia                float64
Wheat imports from Ukraine per capita              float64
Wheat imports from Russia per capita               float64
Wheat imports from Ukraine + Russia per capita     float64
Wheat imports from Ukraine (% imports)             float64
Wheat imports from Russia (% imports)              float64
Wheat imports from Ukraine + Russia (% imports)    float64
Wheat imports from Ukraine (% supply)              float64
Wheat imports from Russia (% supply)               float64
Wheat imports from Ukraine + Russia (% supply)     float64
Entity                                              object
Year                                                 int64
dtype: object

In [158]:
#checking for duplicate values
duplicates = df1.duplicated()
print("\nDuplicate Rows:\n", df1[duplicates])

Duplicate Rows:
 Empty DataFrame
Columns: [Domestic wheat supply, Wheat exports, Wheat imports, Wheat stocks, Net wheat imports, Wheat imports (% domestic supply), Wheat stocks (% domestic supply), Wheat exports per capita, Wheat imports per capita, Net wheat imports per capita, Wheat stocks per capita, Domestic wheat per capita, Wheat imports from Ukraine, Wheat imports from Russia, Wheat imports from Ukraine + Russia, Wheat imports from Ukraine per capita, Wheat imports from Russia per capita, Wheat imports from Ukraine + Russia per capita, Wheat imports from Ukraine (% imports), Wheat imports from Russia (% imports), Wheat imports from Ukraine + Russia (% imports), Wheat imports from Ukraine (% supply), Wheat imports from Russia (% supply), Wheat imports from Ukraine + Russia (% supply), Entity, Year]
Index: []

[0 rows x 26 columns]

In [161]:
#handling columns which can be replaced with zero

df1 = df1.fillna({
    "Wheat exports": 0,
    "Wheat imports": 0,
    "Wheat imports (% domestic supply)": 0,
    "Wheat exports per capita":0,
    "Wheat imports per capita":0,
    "Wheat imports from Ukraine":0,
    "Wheat imports from Russia":0,
    "Wheat imports from Ukraine per capita":0,
    "Wheat imports from Russia per capita":0,
    "Wheat imports from Ukraine (% imports)":0,
    "Wheat imports from Russia (% imports)":0,
    "Wheat imports from Ukraine (% supply)":0,
    "Wheat imports from Russia (% supply)":0
})

In [162]:
#handling other columns which can't be zero

df1["Net wheat imports"] = df1["Wheat imports"]-df1["Wheat exports"]
df1["Net wheat imports per capita"] = df1["Wheat imports per capita"] - df1["Wheat exports per capita"]
df1["Wheat imports from Ukraine + Russia"] = df1["Wheat imports from Ukraine"]+df1["Wheat imports from Russia"]
df1["Wheat imports from Ukraine + Russia per capita"]=df1["Wheat imports from Ukraine per capita"]+df1["Wheat imports from Russia per capita"]
df1["Wheat imports from Ukraine + Russia (% imports)"]=df1["Wheat imports from Ukraine (% imports)"]+df1["Wheat imports from Russia (% imports)"]
df1["Wheat imports from Ukraine + Russia (% supply)"]=df1["Wheat imports from Ukraine (% supply)"]+df1["Wheat imports from Russia (% supply)"]

In [163]:
#checking for missing values
missing_values = df1.isnull().sum()
print("Missing Values:\n", missing_values)

Missing Values:
 Domestic wheat supply                              0
Wheat exports                                      0
Wheat imports                                      0
Wheat stocks                                       0
Net wheat imports                                  0
Wheat imports (% domestic supply)                  0
Wheat stocks (% domestic supply)                   0
Wheat exports per capita                           0
Wheat imports per capita                           0
Net wheat imports per capita                       0
Wheat stocks per capita                            0
Domestic wheat per capita                          0
Wheat imports from Ukraine                         0
Wheat imports from Russia                          0
Wheat imports from Ukraine + Russia                0
Wheat imports from Ukraine per capita              0
Wheat imports from Russia per capita               0
Wheat imports from Ukraine + Russia per capita     0
Wheat imports from Ukraine (% imports)             0
Wheat imports from Russia (% imports)              0
Wheat imports from Ukraine + Russia (% imports)    0
Wheat imports from Ukraine (% supply)              0
Wheat imports from Russia (% supply)               0
Wheat imports from Ukraine + Russia (% supply)     0
Entity                                             0
Year                                               0
dtype: int64

**for df2**

In [164]:
df2

,Domestic maize supply,Maize exports,Maize imports,Maize stocks,Net maize imports,Maize imports (% domestic supply),Maize stocks (% domestic supply),Maize exports per capita,Maize imports per capita,Net maize imports per capita,...,Maize imports from Russia per capita,Maize imports from Ukraine + Russia per capita,Maize imports from Ukraine (% imports),Maize imports from Russia (% imports),Maize imports from Ukraine + Russia (% imports),Maize imports from Ukraine (% supply),Maize imports from Russia (% supply),Maize imports from Ukraine + Russia (% supply),Entity,Year
0,301000,45.0,0.0,0.0,-45.0,NaN,0.000000,0.001542,0.000000,-0.001542,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,2010
1,303000,0.0,2885.0,0.0,2885.0,0.952145,0.000000,0.000000,0.095792,0.095792,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,2011
2,314000,0.0,3874.0,0.0,3874.0,1.233758,0.000000,0.000000,0.124321,0.124321,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,2012
3,313000,0.0,655.0,0.0,655.0,0.209265,0.000000,0.000000,0.020298,0.020298,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,2013
4,370000,1736.0,32788.0,0.0,31052.0,8.392432,0.000000,0.052022,0.982536,0.930514,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1839,1250000,440.0,571775.0,0.0,571335.0,45.706800,0.000000,0.031850,41.389057,41.357206,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2015
1840,1392000,631.0,821672.0,0.0,821041.0,58.982830,0.000000,0.044974,58.563949,58.518975,...,0.565988,NaN,NaN,0.966444,NaN,NaN,0.570474,NaN,Zimbabwe,2016
1841,1632000,2324.0,308267.0,233000.0,305943.0,18.746507,14.276961,0.163241,21.653135,21.489894,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2017
1842,1605000,836.0,92847.0,54000.0,92011.0,5.732773,3.364486,0.057900,6.430377,6.372477,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2018
1843,1140000,1154.0,73601.0,-286000.0,72447.0,6.355000,-25.087719,0.078796,5.025512,4.946716,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2019

In [165]:
#checking for missing values
missing_values2 = df2.isnull().sum()
print("Missing Values:\n", missing_values2)

Missing Values:
 Domestic maize supply                                 0
Maize exports                                       480
Maize imports                                        72
Maize stocks                                         37
Net maize imports                                   480
Maize imports (% domestic supply)                   821
Maize stocks (% domestic supply)                    102
Maize exports per capita                            480
Maize imports per capita                             72
Net maize imports per capita                        480
Maize stocks per capita                              37
Domestic maize per capita                             0
Maize imports from Ukraine                         1352
Maize imports from Russia                          1494
Maize imports from Ukraine + Russia                1563
Maize imports from Ukraine per capita              1352
Maize imports from Russia per capita               1494
Maize imports from Ukraine + Russia per capita     1563
Maize imports from Ukraine (% imports)             1352
Maize imports from Russia (% imports)              1494
Maize imports from Ukraine + Russia (% imports)    1563
Maize imports from Ukraine (% supply)              1353
Maize imports from Russia (% supply)               1495
Maize imports from Ukraine + Russia (% supply)     1563
Entity                                                0
Year                                                  0
dtype: int64

In [166]:
#checking datatype
data_types2 = df2.dtypes
print("\nData Types:\n", data_types2)

Data Types:
 Domestic maize supply                                int64
Maize exports                                      float64
Maize imports                                      float64
Maize stocks                                       float64
Net maize imports                                  float64
Maize imports (% domestic supply)                  float64
Maize stocks (% domestic supply)                   float64
Maize exports per capita                           float64
Maize imports per capita                           float64
Net maize imports per capita                       float64
Maize stocks per capita                            float64
Domestic maize per capita                          float64
Maize imports from Ukraine                         float64
Maize imports from Russia                          float64
Maize imports from Ukraine + Russia                float64
Maize imports from Ukraine per capita              float64
Maize imports from Russia per capita               float64
Maize imports from Ukraine + Russia per capita     float64
Maize imports from Ukraine (% imports)             float64
Maize imports from Russia (% imports)              float64
Maize imports from Ukraine + Russia (% imports)    float64
Maize imports from Ukraine (% supply)              float64
Maize imports from Russia (% supply)               float64
Maize imports from Ukraine + Russia (% supply)     float64
Entity                                              object
Year                                                 int64
dtype: object

In [167]:
#checking for duplicate values
duplicates2 = df2.duplicated()
print("\nDuplicate Rows:\n", df2[duplicates])

Duplicate Rows:
 Empty DataFrame
Columns: [Domestic maize supply, Maize exports, Maize imports, Maize stocks, Net maize imports, Maize imports (% domestic supply), Maize stocks (% domestic supply), Maize exports per capita, Maize imports per capita, Net maize imports per capita, Maize stocks per capita, Domestic maize per capita, Maize imports from Ukraine, Maize imports from Russia, Maize imports from Ukraine + Russia, Maize imports from Ukraine per capita, Maize imports from Russia per capita, Maize imports from Ukraine + Russia per capita, Maize imports from Ukraine (% imports), Maize imports from Russia (% imports), Maize imports from Ukraine + Russia (% imports), Maize imports from Ukraine (% supply), Maize imports from Russia (% supply), Maize imports from Ukraine + Russia (% supply), Entity, Year]
Index: []

[0 rows x 26 columns]

In [168]:
#handling columns which can be replaced with zero

df2 = df2.fillna({
    "Maize exports": 0,
    "Maize imports": 0,
    "Maize stocks": 0,
    "Maize imports (% domestic supply)": 0,
    "Maize stocks (% domestic supply)":0,
    "Maize exports per capita":0,
    "Maize imports per capita":0,
    "Maize stocks per capita":0,
    "Maize imports from Ukraine":0,
    "Maize imports from Russia":0,
    "Maize imports from Ukraine per capita":0,
    "Maize imports from Russia per capita":0,
    "Maize imports from Ukraine (% imports)":0,
    "Maize imports from Russia (% imports)":0,
    "Maize imports from Ukraine (% supply)":0,
    "Maize imports from Russia (% supply)":0
})

In [169]:
#handling other columns which can't be zero

df2["Net maize imports"] = df2["Maize imports"]-df2["Maize exports"]
df2["Net maize imports per capita"] =df2["Maize imports per capita"] - df2["Maize exports per capita"]
df2["Maize imports from Ukraine + Russia"] = df2["Maize imports from Ukraine"]+df2["Maize imports from Russia"]
df2["Maize imports from Ukraine + Russia per capita"]=df2["Maize imports from Ukraine per capita"]+df2["Maize imports from Russia per capita"]
df2["Maize imports from Ukraine + Russia (% imports)"]=df2["Maize imports from Ukraine (% imports)"]+df2["Maize imports from Russia (% imports)"]
df2["Maize imports from Ukraine + Russia (% supply)"]=df2["Maize imports from Ukraine (% supply)"]+df2["Maize imports from Russia (% supply)"]

In [170]:
#checking for missing values
missing_value2 = df2.isnull().sum()
print("Missing Values:\n", missing_value2)

Missing Values:
 Domestic maize supply                              0
Maize exports                                      0
Maize imports                                      0
Maize stocks                                       0
Net maize imports                                  0
Maize imports (% domestic supply)                  0
Maize stocks (% domestic supply)                   0
Maize exports per capita                           0
Maize imports per capita                           0
Net maize imports per capita                       0
Maize stocks per capita                            0
Domestic maize per capita                          0
Maize imports from Ukraine                         0
Maize imports from Russia                          0
Maize imports from Ukraine + Russia                0
Maize imports from Ukraine per capita              0
Maize imports from Russia per capita               0
Maize imports from Ukraine + Russia per capita     0
Maize imports from Ukraine (% imports)             0
Maize imports from Russia (% imports)              0
Maize imports from Ukraine + Russia (% imports)    0
Maize imports from Ukraine (% supply)              0
Maize imports from Russia (% supply)               0
Maize imports from Ukraine + Russia (% supply)     0
Entity                                             0
Year                                               0
dtype: int64

**df3**

In [171]:
df3

,Domestic barley supply,Barley exports,Barley imports,Barley stocks,Net barley imports,Barley imports (% domestic supply),Barley stocks (% domestic supply),Barley exports per capita,Barley imports per capita,Net barley imports per capita,...,Barley imports from Russia per capita,Barley imports from Ukraine + Russia per capita,Barley imports from Ukraine (% imports),Barley imports from Russia (% imports),Barley imports from Ukraine + Russia (% imports),Barley imports from Ukraine (% supply),Barley imports from Russia (% supply),Barley imports from Ukraine + Russia (% supply),Entity,Year
0,449000.0,NaN,3109.0,-9000.0,NaN,NaN,-2.004454,NaN,0.106525,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,2010
1,334000.0,NaN,33514.0,5000.0,NaN,NaN,1.497006,NaN,1.112778,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,2011
2,515000.0,NaN,3607.0,4000.0,NaN,NaN,0.776699,NaN,0.115752,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,2012
3,510000.0,NaN,10000.0,14000.0,NaN,NaN,2.745098,NaN,0.309889,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,2013
4,507000.0,NaN,11108.0,25000.0,NaN,NaN,4.930966,NaN,0.332866,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1839,53000.0,0.0,4774.0,-8000.0,4774.0,9.007547,-15.094340,0.000000,0.345575,0.345575,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2015
1840,52000.0,60.0,3544.0,-3000.0,3484.0,6.700000,-5.769231,0.004276,0.252595,0.248319,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2016
1841,54000.0,NaN,0.0,0.0,NaN,NaN,0.000000,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2017
1842,55000.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2018
1843,54000.0,NaN,0.0,2000.0,NaN,NaN,3.703704,NaN,0.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2019

In [172]:
#checking for missing values
missing_value3 = df3.isnull().sum()
print("Missing Values:\n", missing_value3)

Missing Values:
 Domestic barley supply                                 1
Barley exports                                       889
Barley imports                                       349
Barley stocks                                         50
Net barley imports                                   902
Barley imports (% domestic supply)                  1221
Barley stocks (% domestic supply)                    290
Barley exports per capita                            889
Barley imports per capita                            349
Net barley imports per capita                        902
Barley stocks per capita                              50
Domestic barley per capita                             1
Barley imports from Ukraine                         1562
Barley imports from Russia                          1608
Barley imports from Ukraine + Russia                1708
Barley imports from Ukraine per capita              1562
Barley imports from Russia per capita               1608
Barley imports from Ukraine + Russia per capita     1708
Barley imports from Ukraine (% imports)             1563
Barley imports from Russia (% imports)              1608
Barley imports from Ukraine + Russia (% imports)    1708
Barley imports from Ukraine (% supply)              1563
Barley imports from Russia (% supply)               1608
Barley imports from Ukraine + Russia (% supply)     1708
Entity                                                 0
Year                                                   0
dtype: int64

In [173]:
#checking datatype
data_types3 = df3.dtypes
print("\nData Types:\n", data_types3)

Data Types:
 Domestic barley supply                              float64
Barley exports                                      float64
Barley imports                                      float64
Barley stocks                                       float64
Net barley imports                                  float64
Barley imports (% domestic supply)                  float64
Barley stocks (% domestic supply)                   float64
Barley exports per capita                           float64
Barley imports per capita                           float64
Net barley imports per capita                       float64
Barley stocks per capita                            float64
Domestic barley per capita                          float64
Barley imports from Ukraine                         float64
Barley imports from Russia                          float64
Barley imports from Ukraine + Russia                float64
Barley imports from Ukraine per capita              float64
Barley imports from Russia per capita               float64
Barley imports from Ukraine + Russia per capita     float64
Barley imports from Ukraine (% imports)             float64
Barley imports from Russia (% imports)              float64
Barley imports from Ukraine + Russia (% imports)    float64
Barley imports from Ukraine (% supply)              float64
Barley imports from Russia (% supply)               float64
Barley imports from Ukraine + Russia (% supply)     float64
Entity                                               object
Year                                                  int64
dtype: object

In [174]:
#checking for duplicate values
duplicates3 = df3.duplicated()
print("\nDuplicate Rows:\n", df3[duplicates])

Duplicate Rows:
 Empty DataFrame
Columns: [Domestic barley supply, Barley exports, Barley imports, Barley stocks, Net barley imports, Barley imports (% domestic supply), Barley stocks (% domestic supply), Barley exports per capita, Barley imports per capita, Net barley imports per capita, Barley stocks per capita, Domestic barley per capita, Barley imports from Ukraine, Barley imports from Russia, Barley imports from Ukraine + Russia, Barley imports from Ukraine per capita, Barley imports from Russia per capita, Barley imports from Ukraine + Russia per capita, Barley imports from Ukraine (% imports), Barley imports from Russia (% imports), Barley imports from Ukraine + Russia (% imports), Barley imports from Ukraine (% supply), Barley imports from Russia (% supply), Barley imports from Ukraine + Russia (% supply), Entity, Year]
Index: []

[0 rows x 26 columns]

In [175]:
#handling columns which can be replaced with zero

df3 = df3.fillna({
    "Domestic barley supply":0,
    "Barley exports": 0,
    "Barley imports": 0,
    "Barley stocks": 0,
    "Barley imports (% domestic supply)": 0,
    "Barley stocks (% domestic supply)":0,
    "Barley exports per capita":0,
    "Barley imports per capita":0,
    "Barley stocks per capita":0,
    "Domestic barley per capita":0,
    "Barley imports from Ukraine":0,
    "Barley imports from Russia":0,
    "Barley imports from Ukraine per capita":0,
    "Barley imports from Russia per capita":0,
    "Barley imports from Ukraine (% imports)":0,
    "Barley imports from Russia (% imports)":0,
    "Barley imports from Ukraine (% supply)":0,
    "Barley imports from Russia (% supply)":0
})

In [176]:
#handling other columns which can't be zero

df3["Net barley imports"] = df3["Barley imports"]-df3["Barley exports"]
df3["Net barley imports per capita"] =df3["Barley imports per capita"] - df3["Barley exports per capita"]
df3["Barley imports from Ukraine + Russia"] = df3["Barley imports from Ukraine"]+df3["Barley imports from Russia"]
df3["Barley imports from Ukraine + Russia per capita"]=df3["Barley imports from Ukraine per capita"]+df3["Barley imports from Russia per capita"]
df3["Barley imports from Ukraine + Russia (% imports)"]=df3["Barley imports from Ukraine (% imports)"]+df3["Barley imports from Russia (% imports)"]
df3["Barley imports from Ukraine + Russia (% supply)"]=df3["Barley imports from Ukraine (% supply)"]+df3["Barley imports from Russia (% supply)"]

In [177]:
#checking for missing values
missing_value3 = df3.isnull().sum()
print("Missing Values:\n", missing_value3)

Missing Values:
 Domestic barley supply                              0
Barley exports                                      0
Barley imports                                      0
Barley stocks                                       0
Net barley imports                                  0
Barley imports (% domestic supply)                  0
Barley stocks (% domestic supply)                   0
Barley exports per capita                           0
Barley imports per capita                           0
Net barley imports per capita                       0
Barley stocks per capita                            0
Domestic barley per capita                          0
Barley imports from Ukraine                         0
Barley imports from Russia                          0
Barley imports from Ukraine + Russia                0
Barley imports from Ukraine per capita              0
Barley imports from Russia per capita               0
Barley imports from Ukraine + Russia per capita     0
Barley imports from Ukraine (% imports)             0
Barley imports from Russia (% imports)              0
Barley imports from Ukraine + Russia (% imports)    0
Barley imports from Ukraine (% supply)              0
Barley imports from Russia (% supply)               0
Barley imports from Ukraine + Russia (% supply)     0
Entity                                              0
Year                                                0
dtype: int64

**df4**

In [178]:
df4

,Domestic sunflower oil supply,Sunflower oil exports,Sunflower oil imports,Sunflower oil stocks,Net sunflower oil imports,Sunflower oil imports (% domestic supply),Sunflower oil stocks (% domestic supply),Sunflower oil exports per capita,Sunflower oil imports per capita,Net sunflower oil imports per capita,...,Sunflower oil imports from Russia per capita,Sunflower oil imports from Ukraine + Russia per capita,Sunflower oil imports from Ukraine (% imports),Sunflower oil imports from Russia (% imports),Sunflower oil imports from Ukraine + Russia (% imports),Sunflower oil imports from Ukraine (% supply),Sunflower oil imports from Russia (% supply),Sunflower oil imports from Ukraine + Russia (% supply),Entity,Year
0,15000.0,NaN,14600.0,0.0,NaN,NaN,0.000000,NaN,0.500248,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,2010
1,15000.0,NaN,15000.0,0.0,NaN,NaN,0.000000,NaN,0.498051,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,2011
2,28000.0,NaN,16100.0,-11000.0,NaN,NaN,-39.285714,NaN,0.516665,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,2012
3,39000.0,NaN,22300.0,-16000.0,NaN,NaN,-41.025641,NaN,0.691053,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan,2013
4,40000.0,NaN,37000.0,-2000.0,NaN,NaN,-5.000000,NaN,1.108754,NaN,...,0.880141,0.944448,5.8,79.381081,85.181081,5.365,73.4275,78.7925,Afghanistan,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1839,32000.0,0.0,5036.0,-25000.0,5036.0,15.737500,-78.125000,0.000000,0.364541,0.364541,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2015
1840,43000.0,1.0,2308.0,-40000.0,2307.0,5.365116,-93.023256,0.000071,0.164501,0.164429,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2016
1841,8000.0,NaN,1663.0,-5000.0,NaN,NaN,-62.500000,NaN,0.116812,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2017
1842,3000.0,9.0,950.0,0.0,941.0,31.366667,0.000000,0.000623,0.065795,0.065172,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2018
1843,3000.0,NaN,1359.0,0.0,NaN,NaN,0.000000,NaN,0.092793,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2019

In [179]:
#checking for missing values
missing_value4 = df4.isnull().sum()
print("Missing Values:\n", missing_value4)

Missing Values:
 Domestic sunflower oil supply                                28
Sunflower oil exports                                       634
Sunflower oil imports                                       133
Sunflower oil stocks                                         91
Net sunflower oil imports                                   636
Sunflower oil imports (% domestic supply)                   890
Sunflower oil stocks (% domestic supply)                    464
Sunflower oil exports per capita                            634
Sunflower oil imports per capita                            133
Net sunflower oil imports per capita                        636
Sunflower oil stocks per capita                              91
Domestic sunflower oil per capita                            28
Sunflower oil imports from Ukraine                         1080
Sunflower oil imports from Russia                          1365
Sunflower oil imports from Ukraine + Russia                1428
Sunflower oil imports from Ukraine per capita              1080
Sunflower oil imports from Russia per capita               1365
Sunflower oil imports from Ukraine + Russia per capita     1428
Sunflower oil imports from Ukraine (% imports)             1082
Sunflower oil imports from Russia (% imports)              1365
Sunflower oil imports from Ukraine + Russia (% imports)    1428
Sunflower oil imports from Ukraine (% supply)              1134
Sunflower oil imports from Russia (% supply)               1379
Sunflower oil imports from Ukraine + Russia (% supply)     1438
Entity                                                        0
Year                                                          0
dtype: int64

In [180]:
#checking datatype
data_types4 = df4.dtypes
print("\nData Types:\n", data_types4)

Data Types:
 Domestic sunflower oil supply                              float64
Sunflower oil exports                                      float64
Sunflower oil imports                                      float64
Sunflower oil stocks                                       float64
Net sunflower oil imports                                  float64
Sunflower oil imports (% domestic supply)                  float64
Sunflower oil stocks (% domestic supply)                   float64
Sunflower oil exports per capita                           float64
Sunflower oil imports per capita                           float64
Net sunflower oil imports per capita                       float64
Sunflower oil stocks per capita                            float64
Domestic sunflower oil per capita                          float64
Sunflower oil imports from Ukraine                         float64
Sunflower oil imports from Russia                          float64
Sunflower oil imports from Ukraine + Russia                float64
Sunflower oil imports from Ukraine per capita              float64
Sunflower oil imports from Russia per capita               float64
Sunflower oil imports from Ukraine + Russia per capita     float64
Sunflower oil imports from Ukraine (% imports)             float64
Sunflower oil imports from Russia (% imports)              float64
Sunflower oil imports from Ukraine + Russia (% imports)    float64
Sunflower oil imports from Ukraine (% supply)              float64
Sunflower oil imports from Russia (% supply)               float64
Sunflower oil imports from Ukraine + Russia (% supply)     float64
Entity                                                      object
Year                                                         int64
dtype: object

In [181]:
#checking for duplicate values
duplicates4 = df4.duplicated()
print("\nDuplicate Rows:\n", df4[duplicates])

Duplicate Rows:
 Empty DataFrame
Columns: [Domestic sunflower oil supply, Sunflower oil exports, Sunflower oil imports, Sunflower oil stocks, Net sunflower oil imports, Sunflower oil imports (% domestic supply), Sunflower oil stocks (% domestic supply), Sunflower oil exports per capita, Sunflower oil imports per capita, Net sunflower oil imports per capita, Sunflower oil stocks per capita, Domestic sunflower oil per capita, Sunflower oil imports from Ukraine, Sunflower oil imports from Russia, Sunflower oil imports from Ukraine + Russia, Sunflower oil imports from Ukraine per capita, Sunflower oil imports from Russia per capita, Sunflower oil imports from Ukraine + Russia per capita, Sunflower oil imports from Ukraine (% imports), Sunflower oil imports from Russia (% imports), Sunflower oil imports from Ukraine + Russia (% imports), Sunflower oil imports from Ukraine (% supply), Sunflower oil imports from Russia (% supply), Sunflower oil imports from Ukraine + Russia (% supply), Entity, Year]
Index: []

[0 rows x 26 columns]

In [182]:
#handling columns which can be replaced with zero

df4 = df4.fillna({
    "Domestic sunflower oil supply":0,
    "Sunflower oil exports": 0,
    "Sunflower oil imports": 0,
    "Sunflower oil stocks": 0,
    "Sunflower oil imports (% domestic supply)": 0,
    "Sunflower oil stocks (% domestic supply)":0,
    "Sunflower oil exports per capita":0,
    "Sunflower oil imports per capita":0,
    "Sunflower oil stocks per capita":0,
    "Domestic sunflower oil per capita":0,
    "Sunflower oil imports from Ukraine":0,
    "Sunflower oil imports from Russia":0,
    "Sunflower oil imports from Ukraine per capita":0,
    "Sunflower oil imports from Russia per capita":0,
    "Sunflower oil imports from Ukraine (% imports)":0,
    "Sunflower oil imports from Russia (% imports)":0,
    "Sunflower oil imports from Ukraine (% supply)":0,
    "Sunflower oil imports from Russia (% supply)":0
})

In [183]:
#handling other columns which can't be zero

df4["Net sunflower oil imports"] = df4["Sunflower oil imports"]-df4["Sunflower oil exports"]
df4["Net sunflower oil imports per capita"] =df4["Sunflower oil imports per capita"] - df4["Sunflower oil exports per capita"]
df4["Sunflower oil imports from Ukraine + Russia"] = df4["Sunflower oil imports from Ukraine"]+df4["Sunflower oil imports from Russia"]
df4["Sunflower oil imports from Ukraine + Russia per capita"]=df4["Sunflower oil imports from Ukraine per capita"]+df4["Sunflower oil imports from Russia per capita"]
df4["Sunflower oil imports from Ukraine + Russia (% imports)"]=df4["Sunflower oil imports from Ukraine (% imports)"]+df4["Sunflower oil imports from Russia (% imports)"]
df4["Sunflower oil imports from Ukraine + Russia (% supply)"]=df4["Sunflower oil imports from Ukraine (% supply)"]+df4["Sunflower oil imports from Russia (% supply)"]

In [184]:
#checking for missing values
missing_value4 = df4.isnull().sum()
print("Missing Values:\n", missing_value4)

Missing Values:
 Domestic sunflower oil supply                              0
Sunflower oil exports                                      0
Sunflower oil imports                                      0
Sunflower oil stocks                                       0
Net sunflower oil imports                                  0
Sunflower oil imports (% domestic supply)                  0
Sunflower oil stocks (% domestic supply)                   0
Sunflower oil exports per capita                           0
Sunflower oil imports per capita                           0
Net sunflower oil imports per capita                       0
Sunflower oil stocks per capita                            0
Domestic sunflower oil per capita                          0
Sunflower oil imports from Ukraine                         0
Sunflower oil imports from Russia                          0
Sunflower oil imports from Ukraine + Russia                0
Sunflower oil imports from Ukraine per capita              0
Sunflower oil imports from Russia per capita               0
Sunflower oil imports from Ukraine + Russia per capita     0
Sunflower oil imports from Ukraine (% imports)             0
Sunflower oil imports from Russia (% imports)              0
Sunflower oil imports from Ukraine + Russia (% imports)    0
Sunflower oil imports from Ukraine (% supply)              0
Sunflower oil imports from Russia (% supply)               0
Sunflower oil imports from Ukraine + Russia (% supply)     0
Entity                                                     0
Year                                                       0
dtype: int64

In [187]:
df1.to_csv("wheat.csv",index = False)
df2.to_csv("Maize.csv",index = False)
df3.to_csv("Barley.csv",index = False)
df4.to_csv("Sunflower oil.csv",index = False)

In [188]:
df3.to_excel("Barley1.xlsx",index = False)